version: '3.5'

volumes:
    datavolume:

services:
    db:
        container_name: db
        image: mysql:8.0.23
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        volumes:
            - datavolume:/var/lib/mysql

    php:
        container_name: app
        build:
            context: ./docker/php-fpm
            args:
                ENABLE_PHP_XDEBUG: 1
        ports:
            - "9000:9001"
        volumes:
            - ./project:/var/www/symfony
        depends_on:
            - db

    nginx:
        container_name: nginx
        build: ./docker/nginx
        ports:
            - "80:80"
        depends_on: 
            - php

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8081:80
        depends_on:
            - nginx