# Первый запрос на создание API-токена. Разница между временем на машине и в запросе должна быть не больше 24 часов.
POST http://mysite.loc/api/user/token
Content-Type: application/json

{
    "username": "User0",
    "password": "123456",
    "timestamp": "2020-02-24 00:00:00"
}



###
# Второй запрос на получение "полезных" данных.
# Перед запуском скопируйте ключ из ответа на первый запрос.
GET http://mysite.loc/api/data
Accept: application/json
X-AUTH-TOKEN: 0a7e1e263077e45748ede3e5da9fcdee



###
# Третий, четвертый и пятый запросы для демонстрации что роут на получени токена закрыт для доступа с помощью него. Только логин и пароль.
# Перед запуском скопируйте ключ из ответа на первый запрос в заголовки всех трех запросов ниже.
POST http://mysite.loc/api/user/token
Content-Type: application/json
X-AUTH-TOKEN: 0a7e1e263077e45748ede3e5da9fcdee

{
    "message": "Hello World!"
}

###
POST http://mysite.loc/api/user/token
Content-Type: application/json
X-AUTH-TOKEN: 0a7e1e263077e45748ede3e5da9fcdee

{
    "username": "User0"
}

###
POST http://mysite.loc/api/user/token
Content-Type: application/json
X-AUTH-TOKEN: 0a7e1e263077e45748ede3e5da9fcdee

{
    "username": "User0",
    "password": "bad_password"
}



###
# Шестой запрос на получение "полезных" данных с невалидным токеном.
GET http://mysite.loc/api/data
Accept: application/json
X-AUTH-TOKEN: wrond_token

###
# Седьмой запрос на получение "полезных" данных с помощью логина и пароля.
# Хоть это и бредово body посылать с GET-запросом.
GET http://mysite.loc/api/data
Accept: application/json

{
    "username": "User0",
    "password": "123456"
}

###
# Восьмой запрос на получение "полезных" данных с помощью логина и пароля.
# Используется POST запрос, что должно привести к ошибке.
POST http://mysite.loc/api/data
Accept: application/json

{
    "username": "User0",
    "password": "123456"
}